# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: check PR details
        run: |
          echo "Base branch is: ${BASE_BRANCH}; head branch is ${HEAD_BRANCH}; ref is ${REF}"
        env:
          BASE_BRANCH: ${{ github.base_ref }}
          HEAD_BRANCH: ${{ github.head_ref }}
          REF: ${{ github.ref }}
        if: github.event_name == 'pull_request'
      - name: sets environment
        run: |
          echo "GIT_TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV
          echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV
          echo "LANGUAGE=en" >> $GITHUB_ENV
      - name: Sphinx Docs build with ReadTheDocs Docker
        uses: DavidLeoni/readthedocs-to-actions@v1.2
        with:
          RTD_PRJ_NAME: bede-documentation
          GIT_URL: https://github.com/${{ github.repository }}.git
          GIT_TAG: ${{ env.GIT_TAG }}
          VERSION: ${{ env.VERSION }}
          REQUIREMENTS: requirements.txt
          LANGUAGE: ${{ env.LANGUAGE }}
          RTD_HTML_SINGLE: false
          RTD_HTML_EXT: false
      - name: Show workspace output
        run: |
          tree -aC $GITHUB_WORKSPACE
      - name: Archive built docs
        uses: actions/upload-artifact@v2
        with:
          name: docs
          path: html
